{
 "title": "Engine Overview",
 "tags": [
  "opencraft",
  "engine"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "engine",
    "label": "Engine",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: v.defaultBucket, tag: \"instance\", predicate: (r) => r._measurement == \"propulsion\")"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"notifications\" and r._field == \"severity\")\n  |> last()\n  |> group()\n  |> max()"
    }
   ]
  },
  {
   "title": "RPM (${engine})",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"revolutions\" and r.instance == \"${engine}\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 60.0 }))"
    }
   ]
  },
  {
   "title": "SPEED",
   "type": "stat",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"navigation\" and r._field == \"speedOverGround\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 2.23694 }))"
    }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"temperature\" and r.instance == \"${engine}\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: (r._value - 273.15) * 9.0 / 5.0 + 32.0 }))"
    }
   ]
  },
  {
   "title": "Oil Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"oilPressure\" and r.instance == \"${engine}\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value / 6894.757 }))"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"electrical.batteries\" and r._field == \"voltage\" and r.id == \"house\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Fuel Flow",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "suffix: GPH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"fuel.rate\" and r.instance == \"${engine}\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 3600.0 * 264.172 }))"
    }
   ]
  },
  {
   "title": "Trim Position",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"trim\" and r.instance == \"${engine}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"environment\" and r._field == \"depth.belowTransducer\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 3.28084 }))"
    }
   ]
  },
  {
   "title": "Engine Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "suffix: hrs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"runTime\" and r.instance == \"${engine}\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value / 3600.0 }))"
    }
   ]
  }
 ]
}