{
 "title": "Fuel",
 "tags": [
  "opencraft",
  "engine"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "engine",
    "label": "Engine",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: v.defaultBucket, tag: \"instance\", predicate: (r) => r._measurement == \"propulsion\")"
   }
  ]
 },
 "panels": [
  { "title": "Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fuel Flow",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "repeat": "engine",
   "fieldConfig": { "defaults": { "unit": "suffix: GPH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"fuel.rate\" and r.instance == \"${engine}\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 3600.0 * 264.172 }))"
    }
   ]
  },
  {
   "title": "Fuel Economy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "repeat": "engine",
   "fieldConfig": { "defaults": { "unit": "suffix: nm/gal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"fuel.economy\" and r.instance == \"${engine}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Fuel Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "repeat": "engine",
   "fieldConfig": { "defaults": { "unit": "suffix: gal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"fuel.used\" and r.instance == \"${engine}\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 264.172 }))"
    }
   ]
  },
  {
   "title": "Estimated Range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "repeat": "engine",
   "fieldConfig": { "defaults": { "unit": "suffix: nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -30s)\n  |> filter(fn: (r) => r._measurement == \"propulsion\" and r._field == \"fuel.range\" and r.instance == \"${engine}\")\n  |> last()"
    }
   ]
  }
 ]
}